services:
  whisperx-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: whisperx-service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: whisperx-container
    env_file:
      - .env
    environment:
      - DB_URL=sqlite:////data/records.db
    ports:
      - "8072:8000"
    volumes:
      - "/data/whisperx/cache:/root/.cache"
      - "/data/whisperx:/data"
    tmpfs:
      - /tmp:size=512m,mode=1777,noexec,nosuid,nodev
